# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo/
    docker:
      - image: circleci/golang:1.17.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd v10
            go install -v ./cmd/...
            bash -ex test.sh

